name: Java CI with Maven

on:
  push:
    branches: [ "master", "develop", "release/**" ]
  pull_request:
    branches: [ "master", "develop", "release/**" ]
    types:
      - opened
      - edited
      - synchronize
      - reopened

  workflow_call:
  
jobs:
  
  linter:
    name: linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Linter
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
  
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn test --file pom.xml
  
  build:
    name: build
    needs: [ test, linter ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml -DskipTests=true
